
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 08 17:59:47 CDT 2016
//----------------------------------------------------

package lyaii_analizador_lexico_sintactico_semantico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STD = 8;
  public static final int INCLUDE = 3;
  public static final int PYC = 9;
  public static final int INT = 10;
  public static final int CERRAR_P = 13;
  public static final int ABRIR_P = 12;
  public static final int RETURN = 18;
  public static final int MAYOR_QUE = 7;
  public static final int ASIGNACION = 20;
  public static final int MENOR_QUE = 4;
  public static final int EOF = 0;
  public static final int MAIN = 11;
  public static final int ABRIR_LL = 14;
  public static final int NUMERO = 21;
  public static final int error = 1;
  public static final int LIBRERIA_DLIB = 6;
  public static final int IDENTIFICADOR = 19;
  public static final int COUT = 16;
  public static final int LIBRERIA_IO = 5;
  public static final int NUMERAL = 2;
  public static final int ENDL = 17;
  public static final int CERRAR_LL = 15;
}

